import { ThemeProvider } from "@/components/ThemeProvider";
import TopNav from "../components/layout/TopNav";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: Props) {
  return (
    <ThemeProvider>
      <html lang="en">
        <body>
          <div className="h-screen flex flex-col">
            <TopNav />
            <main className="flex-1 overflow-hidden relative">{children}</main>
          </div>
        </body>
      </html>
    </ThemeProvider>
  );
}
